plugins {
    id 'com.android.library' version '9.3.2' apply false
    id 'org.jetbrains.kotlin.android' version '2.4.10' apply false
}

allprojects {
    buildDir = "${System.getProperty("java.io.tmpdir")}/apps-aars/${rootProject.name}/${project.name}"
}

task clean(type: Delete) {
    delete rootProject.buildDir
}