apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace 'org.swisseph'
    compileSdk 37

    defaultConfig {
        minSdk 21
        targetSdk 36
        versionCode 26
        versionName "2.10.03j7d"
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId 'swisseph'
                artifactId 'swe-android'
                version android.defaultConfig.versionName
                artifact(bundleReleaseAar)
            }
        }
    }
}