plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'org.swisseph'
    compileSdk 37

    defaultConfig {
        minSdk 21
        targetSdk 36
        versionCode 37
        versionName "2.10.03j6f"
    }

    buildFeatures {
        viewBinding false
        dataBinding false
        renderScript false
        buildConfig false
        resValues false
        shaders false
        aidl false
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

androidComponents {
    beforeVariants(selector().withBuildType("debug")) { variant ->
        variant.enable = false
    }
}

android {
    buildTypes {
        release {
            isDefault = true
            debuggable false
            minifyEnabled false
            zipAlignEnabled true
            // Optimization: ignore system-wide ProGuard files if not minifying
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                    "META-INF/LICENSE*",
                    "META-INF/NOTICE*",
                    "META-INF/AL2.0",
                    "META-INF/LGPL2.1",
                    "META-INF/*.kotlin_module"
            ]
        }
    }

    lint {
        quiet true
        abortOnError true
        ignoreWarnings false
        checkTestSources true
        checkDependencies true
        checkReleaseBuilds true
    }

    testOptions {
        unitTests.all {
            enabled = false
        }
    }
}

dependencies {
    // No source code dependencies required for pure resource module
}

publishing {
    publications {
        release(MavenPublication) {
            groupId 'swisseph'
            artifactId 'swe-android'
            version android.defaultConfig.versionName

            afterEvaluate {
                from components.release
            }
        }
    }
}