plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace project.property('AAR_NAMESPACE')
    compileSdk project.property('AAR_COMPILE_SDK') as int

    defaultConfig {
        minSdk project.property('AAR_MIN_SDK') as int
        targetSdk project.property('AAR_TARGET_SDK') as int
        versionCode project.property('AAR_VERSION_CODE') as int
        versionName project.property('AAR_VERSION')
        consumerProguardFiles 'consumer-rules.pro'
    }

    // Optimization: disable debug variant to speed up sync and build
    androidComponents {
        beforeVariants(selector().withBuildType("debug")) { variantBuilder ->
            variantBuilder.enable = false
        }
    }

    buildTypes {
        release {
            isDefault true
            debuggable false
            minifyEnabled false
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig = project.property('AAR_BUILD_CONFIG').toBoolean()
        viewBinding = project.property('AAR_VIEW_BINDING').toBoolean()
        dataBinding = false
        resValues = false
        shaders = false
        aidl = false
        renderScript = false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                    "META-INF/LICENSE*",
                    "META-INF/NOTICE*",
                    "META-INF/AL2.0",
                    "META-INF/LGPL2.1",
                    "META-INF/*.kotlin_module",
                    "**/kotlin/**"
            ]
        }
    }

    lint {
        quiet true
        checkReleaseBuilds false
        abortOnError false
        ignoreWarnings true
        checkTestSources false
        checkDependencies true
    }

    testOptions {
        unitTests.all {
            enabled = false
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    // No source code dependencies required for pure resource module
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                artifactId project.property('AAR_ARTIFACT_ID')
                groupId project.property('AAR_GROUP_ID')
                version project.property('AAR_VERSION')
                from components.release
            }
        }
    }
}
